create table if not exists public.webhook_logs (
  id bigint generated by default as identity primary key,
  logged_at timestamptz not null default now(),
  method text not null check (method in ('GET', 'POST')),
  data jsonb not null default '{}'::jsonb
);

alter table public.webhook_logs enable row level security;

create index if not exists webhook_logs_logged_at_idx
  on public.webhook_logs (logged_at desc);

comment on table public.webhook_logs is
  'Incoming GET and POST requests received by the WhatsApp webhook.';
