create table if not exists public.application_logs (
  id bigint generated by default as identity primary key,
  logged_at timestamptz not null default now(),
  level text not null default 'info'
    check (level in ('info', 'warning', 'error')),
  event text not null,
  message text,
  message_id text,
  data jsonb not null default '{}'::jsonb
);

alter table public.application_logs enable row level security;

create index if not exists application_logs_logged_at_idx
  on public.application_logs (logged_at desc);

create index if not exists application_logs_message_id_idx
  on public.application_logs (message_id)
  where message_id is not null;

comment on table public.application_logs is
  'Structured diagnostics for webhook validation and WhatsApp replies.';
